import Foundation
@main enum CheckRunner {
    @MainActor static func main() async {
        let suite=KenarTests()
        do { try suite.setUpWithError(); try suite.testAntigravityGenerationDecoderIncludesReasoningOnce(); try suite.tearDownWithError(); print("CHECK: testAntigravityGenerationDecoderIncludesReasoningOnce") } catch { CheckSupport.fail("testAntigravityGenerationDecoderIncludesReasoningOnce: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityGenerationDatesReferencedStepsAndRejectsBadUsage(); try suite.tearDownWithError(); print("CHECK: testAntigravityGenerationDatesReferencedStepsAndRejectsBadUsage") } catch { CheckSupport.fail("testAntigravityGenerationDatesReferencedStepsAndRejectsBadUsage: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityDatabaseImportIsPrivateAndDeduplicated(); try suite.tearDownWithError(); print("CHECK: testAntigravityDatabaseImportIsPrivateAndDeduplicated") } catch { CheckSupport.fail("testAntigravityDatabaseImportIsPrivateAndDeduplicated: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityWALUpdatesAndProjectSeparation(); try suite.tearDownWithError(); print("CHECK: testAntigravityWALUpdatesAndProjectSeparation") } catch { CheckSupport.fail("testAntigravityWALUpdatesAndProjectSeparation: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityWorkspaceUnknownAndSchemaVersion(); try suite.tearDownWithError(); print("CHECK: testAntigravityWorkspaceUnknownAndSchemaVersion") } catch { CheckSupport.fail("testAntigravityWorkspaceUnknownAndSchemaVersion: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeQuotaBridgeParsesAccountQuotaWithoutContext(); try suite.tearDownWithError(); print("CHECK: testClaudeQuotaBridgeParsesAccountQuotaWithoutContext") } catch { CheckSupport.fail("testClaudeQuotaBridgeParsesAccountQuotaWithoutContext: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeBridgeFreshnessAndPrivacy(); try suite.tearDownWithError(); print("CHECK: testClaudeBridgeFreshnessAndPrivacy") } catch { CheckSupport.fail("testClaudeBridgeFreshnessAndPrivacy: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeStatusLineSetupKeepsCustomSettings(); try suite.tearDownWithError(); print("CHECK: testClaudeStatusLineSetupKeepsCustomSettings") } catch { CheckSupport.fail("testClaudeStatusLineSetupKeepsCustomSettings: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeWebWorkspaceParsingAndPreferences(); try suite.tearDownWithError(); print("CHECK: testClaudeWebWorkspaceParsingAndPreferences") } catch { CheckSupport.fail("testClaudeWebWorkspaceParsingAndPreferences: \(error)") }
        do { try suite.setUpWithError(); try await suite.testClaudeSourceChangesDiscardInflightResult(); try suite.tearDownWithError(); print("CHECK: testClaudeSourceChangesDiscardInflightResult") } catch { CheckSupport.fail("testClaudeSourceChangesDiscardInflightResult: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityOfficialQuotaAndResetHints(); try suite.tearDownWithError(); print("CHECK: testAntigravityOfficialQuotaAndResetHints") } catch { CheckSupport.fail("testAntigravityOfficialQuotaAndResetHints: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityMissingAndMalformedFieldsStayUnknown(); try suite.tearDownWithError(); print("CHECK: testAntigravityMissingAndMalformedFieldsStayUnknown") } catch { CheckSupport.fail("testAntigravityMissingAndMalformedFieldsStayUnknown: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityBridgePrivacyAndRepaintDeduplication(); try suite.tearDownWithError(); print("CHECK: testAntigravityBridgePrivacyAndRepaintDeduplication") } catch { CheckSupport.fail("testAntigravityBridgePrivacyAndRepaintDeduplication: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityMissingAndStaleSource(); try suite.tearDownWithError(); print("CHECK: testAntigravityMissingAndStaleSource") } catch { CheckSupport.fail("testAntigravityMissingAndStaleSource: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityInstallerPreservesSettingsAndCanReconnect(); try suite.tearDownWithError(); print("CHECK: testAntigravityInstallerPreservesSettingsAndCanReconnect") } catch { CheckSupport.fail("testAntigravityInstallerPreservesSettingsAndCanReconnect: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityInstallerRefusesCustomOrBrokenSettings(); try suite.tearDownWithError(); print("CHECK: testAntigravityInstallerRefusesCustomOrBrokenSettings") } catch { CheckSupport.fail("testAntigravityInstallerRefusesCustomOrBrokenSettings: \(error)") }
        do { try suite.setUpWithError(); try suite.testAntigravityPreferenceMigration(); try suite.tearDownWithError(); print("CHECK: testAntigravityPreferenceMigration") } catch { CheckSupport.fail("testAntigravityPreferenceMigration: \(error)") }
        do { try suite.setUpWithError(); try await suite.testAntigravityReplayDoesNotDuplicateHistory(); try suite.tearDownWithError(); print("CHECK: testAntigravityReplayDoesNotDuplicateHistory") } catch { CheckSupport.fail("testAntigravityReplayDoesNotDuplicateHistory: \(error)") }
        do { try suite.setUpWithError(); suite.testGeminiModelsAndMissingQuota(); try suite.tearDownWithError(); print("CHECK: testGeminiModelsAndMissingQuota") } catch { CheckSupport.fail("testGeminiModelsAndMissingQuota: \(error)") }
        do { try suite.setUpWithError(); suite.testGeminiInvalidFractionsAndMalformedResponse(); try suite.tearDownWithError(); print("CHECK: testGeminiInvalidFractionsAndMalformedResponse") } catch { CheckSupport.fail("testGeminiInvalidFractionsAndMalformedResponse: \(error)") }
        do { try suite.setUpWithError(); suite.testGeminiMultipleQuotaTypesHaveStableIDs(); try suite.tearDownWithError(); print("CHECK: testGeminiMultipleQuotaTypesHaveStableIDs") } catch { CheckSupport.fail("testGeminiMultipleQuotaTypesHaveStableIDs: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeLegacyAndNewModels(); try suite.tearDownWithError(); print("CHECK: testClaudeLegacyAndNewModels") } catch { CheckSupport.fail("testClaudeLegacyAndNewModels: \(error)") }
        do { try suite.setUpWithError(); try suite.testPreviewUsesProviderSpecificQuotaSchemas(); try suite.tearDownWithError(); print("CHECK: testPreviewUsesProviderSpecificQuotaSchemas") } catch { CheckSupport.fail("testPreviewUsesProviderSpecificQuotaSchemas: \(error)") }
        do { try suite.setUpWithError(); suite.testCodexResetPrefersAbsoluteTimestamp(); try suite.tearDownWithError(); print("CHECK: testCodexResetPrefersAbsoluteTimestamp") } catch { CheckSupport.fail("testCodexResetPrefersAbsoluteTimestamp: \(error)") }
        do { try suite.setUpWithError(); suite.testCursorUnlimitedHasNoFakeZero(); try suite.tearDownWithError(); print("CHECK: testCursorUnlimitedHasNoFakeZero") } catch { CheckSupport.fail("testCursorUnlimitedHasNoFakeZero: \(error)") }
        do { try suite.setUpWithError(); suite.testMissingLoginNeverShowsDemoValues(); try suite.tearDownWithError(); print("CHECK: testMissingLoginNeverShowsDemoValues") } catch { CheckSupport.fail("testMissingLoginNeverShowsDemoValues: \(error)") }
        do { try suite.setUpWithError(); suite.testInvalidPercentAndUnknownReset(); try suite.tearDownWithError(); print("CHECK: testInvalidPercentAndUnknownReset") } catch { CheckSupport.fail("testInvalidPercentAndUnknownReset: \(error)") }
        do { try suite.setUpWithError(); suite.testCountdownExpiresWithoutClaimingFreshQuota(); try suite.tearDownWithError(); print("CHECK: testCountdownExpiresWithoutClaimingFreshQuota") } catch { CheckSupport.fail("testCountdownExpiresWithoutClaimingFreshQuota: \(error)") }
        do { try suite.setUpWithError(); try suite.testNotificationRestartDeduplication(); try suite.tearDownWithError(); print("CHECK: testNotificationRestartDeduplication") } catch { CheckSupport.fail("testNotificationRestartDeduplication: \(error)") }
        do { try suite.setUpWithError(); suite.testNotificationNewPeriodAndResetTolerance(); try suite.tearDownWithError(); print("CHECK: testNotificationNewPeriodAndResetTolerance") } catch { CheckSupport.fail("testNotificationNewPeriodAndResetTolerance: \(error)") }
        do { try suite.setUpWithError(); suite.testNotificationProvidersAndMetersAreIndependent(); try suite.tearDownWithError(); print("CHECK: testNotificationProvidersAndMetersAreIndependent") } catch { CheckSupport.fail("testNotificationProvidersAndMetersAreIndependent: \(error)") }
        do { try suite.setUpWithError(); try suite.testHistorySeparatesResetPeriodsAndPrunesOldSamples(); try suite.tearDownWithError(); print("CHECK: testHistorySeparatesResetPeriodsAndPrunesOldSamples") } catch { CheckSupport.fail("testHistorySeparatesResetPeriodsAndPrunesOldSamples: \(error)") }
        do { try suite.setUpWithError(); try suite.testFailedAndDemoSnapshotsNeverEnterHistory(); try suite.tearDownWithError(); print("CHECK: testFailedAndDemoSnapshotsNeverEnterHistory") } catch { CheckSupport.fail("testFailedAndDemoSnapshotsNeverEnterHistory: \(error)") }
        do { try suite.setUpWithError(); try suite.testStreamingEventsKeepMaximumAndDoNotMixProviders(); try suite.tearDownWithError(); print("CHECK: testStreamingEventsKeepMaximumAndDoNotMixProviders") } catch { CheckSupport.fail("testStreamingEventsKeepMaximumAndDoNotMixProviders: \(error)") }
        do { try suite.setUpWithError(); try suite.testLatestSessionAndDifferentProjects(); try suite.tearDownWithError(); print("CHECK: testLatestSessionAndDifferentProjects") } catch { CheckSupport.fail("testLatestSessionAndDifferentProjects: \(error)") }
        do { try suite.setUpWithError(); try suite.testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere(); try suite.tearDownWithError(); print("CHECK: testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere") } catch { CheckSupport.fail("testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere: \(error)") }
        do { try suite.setUpWithError(); suite.testAllEdgesFitNegativeOriginDisplayAndLargeContent(); try suite.tearDownWithError(); print("CHECK: testAllEdgesFitNegativeOriginDisplayAndLargeContent") } catch { CheckSupport.fail("testAllEdgesFitNegativeOriginDisplayAndLargeContent: \(error)") }
        do { try suite.setUpWithError(); await suite.testOfflinePreservesLastSuccessfulMeasurement(); try suite.tearDownWithError(); print("CHECK: testOfflinePreservesLastSuccessfulMeasurement") } catch { CheckSupport.fail("testOfflinePreservesLastSuccessfulMeasurement: \(error)") }
        do { try suite.setUpWithError(); try suite.testTranscriptImportAllThreeProvidersAndPrivacy(); try suite.tearDownWithError(); print("CHECK: testTranscriptImportAllThreeProvidersAndPrivacy") } catch { CheckSupport.fail("testTranscriptImportAllThreeProvidersAndPrivacy: \(error)") }
        do { try suite.setUpWithError(); try suite.testGeminiJSONLStreamingAndIncompleteLine(); try suite.tearDownWithError(); print("CHECK: testGeminiJSONLStreamingAndIncompleteLine") } catch { CheckSupport.fail("testGeminiJSONLStreamingAndIncompleteLine: \(error)") }
        do { try suite.setUpWithError(); suite.testRepeatedGeminiBucketsSelectMostConstrainedQuota(); try suite.tearDownWithError(); print("CHECK: testRepeatedGeminiBucketsSelectMostConstrainedQuota") } catch { CheckSupport.fail("testRepeatedGeminiBucketsSelectMostConstrainedQuota: \(error)") }
        do { try suite.setUpWithError(); suite.testCredentialsCannotFollowCrossOriginRedirect(); try suite.tearDownWithError(); print("CHECK: testCredentialsCannotFollowCrossOriginRedirect") } catch { CheckSupport.fail("testCredentialsCannotFollowCrossOriginRedirect: \(error)") }
        do { try suite.setUpWithError(); suite.testChartDownsamplingPreservesExtremaAndPeriods(); try suite.tearDownWithError(); print("CHECK: testChartDownsamplingPreservesExtremaAndPeriods") } catch { CheckSupport.fail("testChartDownsamplingPreservesExtremaAndPeriods: \(error)") }
        do { try suite.setUpWithError(); try suite.testScopedQuotaAttributionExcludesOtherModels(); try suite.tearDownWithError(); print("CHECK: testScopedQuotaAttributionExcludesOtherModels") } catch { CheckSupport.fail("testScopedQuotaAttributionExcludesOtherModels: \(error)") }
        do { try suite.setUpWithError(); try suite.testFailedImportRollsBackCursorAndCanBeRetried(); try suite.tearDownWithError(); print("CHECK: testFailedImportRollsBackCursorAndCanBeRetried") } catch { CheckSupport.fail("testFailedImportRollsBackCursorAndCanBeRetried: \(error)") }
        do { try suite.setUpWithError(); suite.testIslandOutlineAttachesToChosenEdge(); try suite.tearDownWithError(); print("CHECK: testIslandOutlineAttachesToChosenEdge") } catch { CheckSupport.fail("testIslandOutlineAttachesToChosenEdge: \(error)") }
        do { try suite.setUpWithError(); try suite.testIslandWidthMigrationKeepsCustomSettings(); try suite.tearDownWithError(); print("CHECK: testIslandWidthMigrationKeepsCustomSettings") } catch { CheckSupport.fail("testIslandWidthMigrationKeepsCustomSettings: \(error)") }
        do { try suite.setUpWithError(); suite.testCompactIslandOnlyShowsConnectedProviders(); try suite.tearDownWithError(); print("CHECK: testCompactIslandOnlyShowsConnectedProviders") } catch { CheckSupport.fail("testCompactIslandOnlyShowsConnectedProviders: \(error)") }
        do { try suite.setUpWithError(); suite.testCompactIslandTracksExpiryAndRecovery(); try suite.tearDownWithError(); print("CHECK: testCompactIslandTracksExpiryAndRecovery") } catch { CheckSupport.fail("testCompactIslandTracksExpiryAndRecovery: \(error)") }
        do { try suite.setUpWithError(); try suite.testLegacyVerticalEdgeMigrationKeepsPreferences(); try suite.tearDownWithError(); print("CHECK: testLegacyVerticalEdgeMigrationKeepsPreferences") } catch { CheckSupport.fail("testLegacyVerticalEdgeMigrationKeepsPreferences: \(error)") }
        do { try suite.setUpWithError(); suite.testHoverExitRespondsImmediatelyAndRespectsPin(); try suite.tearDownWithError(); print("CHECK: testHoverExitRespondsImmediatelyAndRespectsPin") } catch { CheckSupport.fail("testHoverExitRespondsImmediatelyAndRespectsPin: \(error)") }
        do { try suite.setUpWithError(); try suite.testEnglishLanguagePersistenceAndFormatting(); try suite.tearDownWithError(); print("CHECK: testEnglishLanguagePersistenceAndFormatting") } catch { CheckSupport.fail("testEnglishLanguagePersistenceAndFormatting: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeKeychainFailuresAreNotMissingLogin(); try suite.tearDownWithError(); print("CHECK: testClaudeKeychainFailuresAreNotMissingLogin") } catch { CheckSupport.fail("testClaudeKeychainFailuresAreNotMissingLogin: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeLoginRecoveryHasNoNegativeCache(); try suite.tearDownWithError(); print("CHECK: testClaudeLoginRecoveryHasNoNegativeCache") } catch { CheckSupport.fail("testClaudeLoginRecoveryHasNoNegativeCache: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache(); try suite.tearDownWithError(); print("CHECK: testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache") } catch { CheckSupport.fail("testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeExpiredAndMalformedCredentialsStayDistinct(); try suite.tearDownWithError(); print("CHECK: testClaudeExpiredAndMalformedCredentialsStayDistinct") } catch { CheckSupport.fail("testClaudeExpiredAndMalformedCredentialsStayDistinct: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeFailedExplicitCheckCannotReviveOldCache(); try suite.tearDownWithError(); print("CHECK: testClaudeFailedExplicitCheckCannotReviveOldCache") } catch { CheckSupport.fail("testClaudeFailedExplicitCheckCannotReviveOldCache: \(error)") }
        do { try suite.setUpWithError(); try await suite.testRetryOnlyFetchesSelectedProviderWithInteractiveIntent(); try suite.tearDownWithError(); print("CHECK: testRetryOnlyFetchesSelectedProviderWithInteractiveIntent") } catch { CheckSupport.fail("testRetryOnlyFetchesSelectedProviderWithInteractiveIntent: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeBackgroundKeychainReadCannotShowPermissionUI(); try suite.tearDownWithError(); print("CHECK: testClaudeBackgroundKeychainReadCannotShowPermissionUI") } catch { CheckSupport.fail("testClaudeBackgroundKeychainReadCannotShowPermissionUI: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeRejectedTokenWaitsForRotationWithoutInteraction(); try suite.tearDownWithError(); print("CHECK: testClaudeRejectedTokenWaitsForRotationWithoutInteraction") } catch { CheckSupport.fail("testClaudeRejectedTokenWaitsForRotationWithoutInteraction: \(error)") }
        do { try suite.setUpWithError(); try await suite.testClaudeAutomaticRecoveryIsSilentAndProviderSpecific(); try suite.tearDownWithError(); print("CHECK: testClaudeAutomaticRecoveryIsSilentAndProviderSpecific") } catch { CheckSupport.fail("testClaudeAutomaticRecoveryIsSilentAndProviderSpecific: \(error)") }
        do { try suite.setUpWithError(); try await suite.testClaudeRecoveryDoesNotPollHealthyOrRateLimitedAccounts(); try suite.tearDownWithError(); print("CHECK: testClaudeRecoveryDoesNotPollHealthyOrRateLimitedAccounts") } catch { CheckSupport.fail("testClaudeRecoveryDoesNotPollHealthyOrRateLimitedAccounts: \(error)") }
        print("\(CheckSupport.failures == 0 ? "PASS" : "FAIL"): 62 scenarios, \(CheckSupport.failures) failures")
        exit(CheckSupport.failures == 0 ? 0 : 1)
    }
}
