import Foundation
@main enum CheckRunner {
    @MainActor static func main() async {
        let suite=KenarTests()
        do { try suite.setUpWithError(); suite.testGeminiModelsAndMissingQuota(); try suite.tearDownWithError(); print("CHECK: testGeminiModelsAndMissingQuota") } catch { CheckSupport.fail("testGeminiModelsAndMissingQuota: \(error)") }
        do { try suite.setUpWithError(); suite.testGeminiInvalidFractionsAndMalformedResponse(); try suite.tearDownWithError(); print("CHECK: testGeminiInvalidFractionsAndMalformedResponse") } catch { CheckSupport.fail("testGeminiInvalidFractionsAndMalformedResponse: \(error)") }
        do { try suite.setUpWithError(); suite.testGeminiMultipleQuotaTypesHaveStableIDs(); try suite.tearDownWithError(); print("CHECK: testGeminiMultipleQuotaTypesHaveStableIDs") } catch { CheckSupport.fail("testGeminiMultipleQuotaTypesHaveStableIDs: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeLegacyAndNewModels(); try suite.tearDownWithError(); print("CHECK: testClaudeLegacyAndNewModels") } catch { CheckSupport.fail("testClaudeLegacyAndNewModels: \(error)") }
        do { try suite.setUpWithError(); suite.testCodexResetPrefersAbsoluteTimestamp(); try suite.tearDownWithError(); print("CHECK: testCodexResetPrefersAbsoluteTimestamp") } catch { CheckSupport.fail("testCodexResetPrefersAbsoluteTimestamp: \(error)") }
        do { try suite.setUpWithError(); suite.testCursorUnlimitedHasNoFakeZero(); try suite.tearDownWithError(); print("CHECK: testCursorUnlimitedHasNoFakeZero") } catch { CheckSupport.fail("testCursorUnlimitedHasNoFakeZero: \(error)") }
        do { try suite.setUpWithError(); suite.testMissingLoginNeverShowsDemoValues(); try suite.tearDownWithError(); print("CHECK: testMissingLoginNeverShowsDemoValues") } catch { CheckSupport.fail("testMissingLoginNeverShowsDemoValues: \(error)") }
        do { try suite.setUpWithError(); suite.testInvalidPercentAndUnknownReset(); try suite.tearDownWithError(); print("CHECK: testInvalidPercentAndUnknownReset") } catch { CheckSupport.fail("testInvalidPercentAndUnknownReset: \(error)") }
        do { try suite.setUpWithError(); suite.testCountdownExpiresWithoutClaimingFreshQuota(); try suite.tearDownWithError(); print("CHECK: testCountdownExpiresWithoutClaimingFreshQuota") } catch { CheckSupport.fail("testCountdownExpiresWithoutClaimingFreshQuota: \(error)") }
        do { try suite.setUpWithError(); try suite.testNotificationRestartDeduplication(); try suite.tearDownWithError(); print("CHECK: testNotificationRestartDeduplication") } catch { CheckSupport.fail("testNotificationRestartDeduplication: \(error)") }
        do { try suite.setUpWithError(); suite.testNotificationNewPeriodAndResetTolerance(); try suite.tearDownWithError(); print("CHECK: testNotificationNewPeriodAndResetTolerance") } catch { CheckSupport.fail("testNotificationNewPeriodAndResetTolerance: \(error)") }
        do { try suite.setUpWithError(); suite.testNotificationProvidersAndMetersAreIndependent(); try suite.tearDownWithError(); print("CHECK: testNotificationProvidersAndMetersAreIndependent") } catch { CheckSupport.fail("testNotificationProvidersAndMetersAreIndependent: \(error)") }
        do { try suite.setUpWithError(); try suite.testHistorySeparatesResetPeriodsAndPrunesOldSamples(); try suite.tearDownWithError(); print("CHECK: testHistorySeparatesResetPeriodsAndPrunesOldSamples") } catch { CheckSupport.fail("testHistorySeparatesResetPeriodsAndPrunesOldSamples: \(error)") }
        do { try suite.setUpWithError(); try suite.testFailedAndDemoSnapshotsNeverEnterHistory(); try suite.tearDownWithError(); print("CHECK: testFailedAndDemoSnapshotsNeverEnterHistory") } catch { CheckSupport.fail("testFailedAndDemoSnapshotsNeverEnterHistory: \(error)") }
        do { try suite.setUpWithError(); try suite.testStreamingEventsKeepMaximumAndDoNotMixProviders(); try suite.tearDownWithError(); print("CHECK: testStreamingEventsKeepMaximumAndDoNotMixProviders") } catch { CheckSupport.fail("testStreamingEventsKeepMaximumAndDoNotMixProviders: \(error)") }
        do { try suite.setUpWithError(); try suite.testLatestSessionAndDifferentProjects(); try suite.tearDownWithError(); print("CHECK: testLatestSessionAndDifferentProjects") } catch { CheckSupport.fail("testLatestSessionAndDifferentProjects: \(error)") }
        do { try suite.setUpWithError(); try suite.testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere(); try suite.tearDownWithError(); print("CHECK: testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere") } catch { CheckSupport.fail("testAttributionDoesNotAssignBaselineOrResetAndKeepsElsewhere: \(error)") }
        do { try suite.setUpWithError(); suite.testAllEdgesFitNegativeOriginDisplayAndLargeContent(); try suite.tearDownWithError(); print("CHECK: testAllEdgesFitNegativeOriginDisplayAndLargeContent") } catch { CheckSupport.fail("testAllEdgesFitNegativeOriginDisplayAndLargeContent: \(error)") }
        do { try suite.setUpWithError(); await suite.testOfflinePreservesLastSuccessfulMeasurement(); try suite.tearDownWithError(); print("CHECK: testOfflinePreservesLastSuccessfulMeasurement") } catch { CheckSupport.fail("testOfflinePreservesLastSuccessfulMeasurement: \(error)") }
        do { try suite.setUpWithError(); try suite.testTranscriptImportAllThreeProvidersAndPrivacy(); try suite.tearDownWithError(); print("CHECK: testTranscriptImportAllThreeProvidersAndPrivacy") } catch { CheckSupport.fail("testTranscriptImportAllThreeProvidersAndPrivacy: \(error)") }
        do { try suite.setUpWithError(); try suite.testGeminiJSONLStreamingAndIncompleteLine(); try suite.tearDownWithError(); print("CHECK: testGeminiJSONLStreamingAndIncompleteLine") } catch { CheckSupport.fail("testGeminiJSONLStreamingAndIncompleteLine: \(error)") }
        do { try suite.setUpWithError(); suite.testRepeatedGeminiBucketsSelectMostConstrainedQuota(); try suite.tearDownWithError(); print("CHECK: testRepeatedGeminiBucketsSelectMostConstrainedQuota") } catch { CheckSupport.fail("testRepeatedGeminiBucketsSelectMostConstrainedQuota: \(error)") }
        do { try suite.setUpWithError(); suite.testCredentialsCannotFollowCrossOriginRedirect(); try suite.tearDownWithError(); print("CHECK: testCredentialsCannotFollowCrossOriginRedirect") } catch { CheckSupport.fail("testCredentialsCannotFollowCrossOriginRedirect: \(error)") }
        do { try suite.setUpWithError(); suite.testChartDownsamplingPreservesExtremaAndPeriods(); try suite.tearDownWithError(); print("CHECK: testChartDownsamplingPreservesExtremaAndPeriods") } catch { CheckSupport.fail("testChartDownsamplingPreservesExtremaAndPeriods: \(error)") }
        do { try suite.setUpWithError(); try suite.testScopedQuotaAttributionExcludesOtherModels(); try suite.tearDownWithError(); print("CHECK: testScopedQuotaAttributionExcludesOtherModels") } catch { CheckSupport.fail("testScopedQuotaAttributionExcludesOtherModels: \(error)") }
        do { try suite.setUpWithError(); try suite.testFailedImportRollsBackCursorAndCanBeRetried(); try suite.tearDownWithError(); print("CHECK: testFailedImportRollsBackCursorAndCanBeRetried") } catch { CheckSupport.fail("testFailedImportRollsBackCursorAndCanBeRetried: \(error)") }
        do { try suite.setUpWithError(); suite.testIslandOutlineAttachesToChosenEdge(); try suite.tearDownWithError(); print("CHECK: testIslandOutlineAttachesToChosenEdge") } catch { CheckSupport.fail("testIslandOutlineAttachesToChosenEdge: \(error)") }
        do { try suite.setUpWithError(); try suite.testIslandWidthMigrationKeepsCustomSettings(); try suite.tearDownWithError(); print("CHECK: testIslandWidthMigrationKeepsCustomSettings") } catch { CheckSupport.fail("testIslandWidthMigrationKeepsCustomSettings: \(error)") }
        do { try suite.setUpWithError(); suite.testCompactIslandOnlyShowsConnectedProviders(); try suite.tearDownWithError(); print("CHECK: testCompactIslandOnlyShowsConnectedProviders") } catch { CheckSupport.fail("testCompactIslandOnlyShowsConnectedProviders: \(error)") }
        do { try suite.setUpWithError(); suite.testCompactIslandTracksExpiryAndRecovery(); try suite.tearDownWithError(); print("CHECK: testCompactIslandTracksExpiryAndRecovery") } catch { CheckSupport.fail("testCompactIslandTracksExpiryAndRecovery: \(error)") }
        do { try suite.setUpWithError(); try suite.testLegacyVerticalEdgeMigrationKeepsPreferences(); try suite.tearDownWithError(); print("CHECK: testLegacyVerticalEdgeMigrationKeepsPreferences") } catch { CheckSupport.fail("testLegacyVerticalEdgeMigrationKeepsPreferences: \(error)") }
        do { try suite.setUpWithError(); suite.testHoverExitRespondsImmediatelyAndRespectsPin(); try suite.tearDownWithError(); print("CHECK: testHoverExitRespondsImmediatelyAndRespectsPin") } catch { CheckSupport.fail("testHoverExitRespondsImmediatelyAndRespectsPin: \(error)") }
        do { try suite.setUpWithError(); try suite.testEnglishLanguagePersistenceAndFormatting(); try suite.tearDownWithError(); print("CHECK: testEnglishLanguagePersistenceAndFormatting") } catch { CheckSupport.fail("testEnglishLanguagePersistenceAndFormatting: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeKeychainFailuresAreNotMissingLogin(); try suite.tearDownWithError(); print("CHECK: testClaudeKeychainFailuresAreNotMissingLogin") } catch { CheckSupport.fail("testClaudeKeychainFailuresAreNotMissingLogin: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeLoginRecoveryHasNoNegativeCache(); try suite.tearDownWithError(); print("CHECK: testClaudeLoginRecoveryHasNoNegativeCache") } catch { CheckSupport.fail("testClaudeLoginRecoveryHasNoNegativeCache: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache(); try suite.tearDownWithError(); print("CHECK: testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache") } catch { CheckSupport.fail("testClaudeExplicitRetryReadsRotatedSourceInsteadOfCache: \(error)") }
        do { try suite.setUpWithError(); suite.testClaudeExpiredAndMalformedCredentialsStayDistinct(); try suite.tearDownWithError(); print("CHECK: testClaudeExpiredAndMalformedCredentialsStayDistinct") } catch { CheckSupport.fail("testClaudeExpiredAndMalformedCredentialsStayDistinct: \(error)") }
        do { try suite.setUpWithError(); try suite.testClaudeFailedExplicitCheckCannotReviveOldCache(); try suite.tearDownWithError(); print("CHECK: testClaudeFailedExplicitCheckCannotReviveOldCache") } catch { CheckSupport.fail("testClaudeFailedExplicitCheckCannotReviveOldCache: \(error)") }
        do { try suite.setUpWithError(); try await suite.testRetryOnlyFetchesSelectedProviderWithInteractiveIntent(); try suite.tearDownWithError(); print("CHECK: testRetryOnlyFetchesSelectedProviderWithInteractiveIntent") } catch { CheckSupport.fail("testRetryOnlyFetchesSelectedProviderWithInteractiveIntent: \(error)") }
        print("\(CheckSupport.failures == 0 ? "PASS" : "FAIL"): 39 scenarios, \(CheckSupport.failures) failures")
        exit(CheckSupport.failures == 0 ? 0 : 1)
    }
}
